"""empty message

Revision ID: 44ca71d01ed5
Revises: 538eeb160af6
Create Date: 2015-12-04 04:31:14.352396

"""

# revision identifiers, used by Alembic.
revision = '44ca71d01ed5'
down_revision = '538eeb160af6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('sched_interval', sa.Integer(), nullable=True))
    op.add_column('account', sa.Column('sched_last_run', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'sched_last_run')
    op.drop_column('account', 'sched_interval')
    ### end Alembic commands ###
